exports.ROOM_NO = "room-";
exports.SYS_USER="sys-user-";

exports.ROOM_STATE = {
    "INIT":0,
    "NOT_ROOM_NUMBER":1,
    "USER_ENTER_FINISHED":2,
    "ROOM_PLAYING":3,
    "ROOM_PRE_GAME_OVER":4,
    "ROOM_FULL":5
}

// exports.PACKET_RESULT ={
//     "SUCCESS":0,
//     "ERROR_PARAMETER":1,

//     "ERROR_CREATE_ROOM_DUPLICATION":100,
//     "ERROR_CREATE_ROOM_NULL":101,
//     "ERROR_CREATE_REDIS_1":102,
//     "ERROR_CREATE_REDIS_2":103,
//     "ERROR_CREATE_REDIS_3":104,

//     "ERROR_ENTER_ROOM":200,
//     "ERROR_ENTER_ROOM_ROOM_NULL":201,
//     "ERROR_ENTER_USER_NULL":202,
//     "ERROR_ENTER_ROOM_GAME_PLAYING":203,
//     "ERROR_ENTER_ROOM_NOT_PASSWORD":204,

//     "ERROR_LEAVE_ROOM_ROOM_NULL":301,
//     "ERROR_LEAVE_ROOM_USER_NULL":302,
//     "ERROR_LEAVE_ROOM_WITHDRAW":303,


//     "ERROR_GAME_READY_ROOM_NULL":400,
//     "ERROR_GAME_READY_USER_NULL":401,
//     "ERROR_GAME_READY_OTHER_USER_NULL":402,
//     "ERROR_GAME_READY_GAME_START":403,
//     "ERROR_GAME_READY_GAME_PLAY_READY":404,

//     "ERROR_NEW_WORD_ROOM_NULL":500,
//     "ERROR_NEW_WORD_USER_NULL":501,
//     "ERROR_NEW_WORD_OTHER_USER_NULL":502,
//     "ERROR_NEW_WORD_NOT_GAMEPLAYING":503,

//     "ERROR_CHECK_WORD_ROOM_NULL":600,
//     "ERROR_CHECK_WORD_USER_NULL":601,
//     "ERROR_CHECK_WORD_OTHER_USER_NULL":602,
//     "ERROR_CHECK_WORD_WORD_NULL":603,
//     "ERROR_CHECK_WORD_WORD_FAIL":604,  //단어가 틀림

//     "ERROR_PRE_GAME_OVER_ROOM_NULL":700,
//     "ERROR_PRE_GAME_OVER_USER_NULL":701,
//     "ERROR_PRE_GAME_OVER_OTHER_USER_NULL":702,
//     "ERROR_PRE_GAME_OVER_FAIL":703,

//     "ERROR_GAME_OVER_ROOM_NULL":800,
//     "ERROR_GAME_OVER_USER_NULL":801,
//     "ERROR_GAME_OVER_OTHER_USER_NULL":802,
//     "ERROR_GAME_OVER_FAIL":803,

//     "ERROR_INPUT_WORD_TIME_OVER_ROOM_NULL":900,
//     "ERROR_INPUT_WORD_TIME_OVER_USER_NULL":901,
//     "ERROR_INPUT_WORD_TIME_OVER_OTHER_USER_NULL":902,
//     "ERROR_INPUT_WORD_TIME_OVER_OTHER_HEART_COUNT_NULL":903,
//     "ERROR_INPUT_WORD_TIME_OVER_FAIL":904,

//     "ERROR_COIN_TOWER_FALL_ROOM_NULL":1000,
//     "ERROR_COIN_TOWER_FALL_USER_NULL":1001,
//     "ERROR_COIN_TOWER_FALL_OTHER_USER_NULL":1002,
//     "ERROR_COIN_TOWER_FALL_HEART_COUNT_NULL":1003,

    

//     "ERROR_GAME_RESULT_ROOM_NULL":1004,
//     "ERROR_GAME_RESULT_USER_NULL":1005,
//     "ERROR_GAME_RESULT_OTHER_USER_NULL":1006,
//     "ERROR_GAME_RESULT_GAME_END":1007


// }



exports.USER_STATE = {
    "READY":0,
    "PLAYING":1,
    "PRE_GAME_OVER":2,
    "GAME_OVER":3
}

/*
콤보 1,2는 공격하지 못함
콤보 공격은 3,4,5,6 일 경우에만 발동

콤보 단어는 단어를 붙혀서 출력한다 (예: 아버지가방에들어가신다)
 */

exports.COMBO_ATTACK_TYPYE = {
    "ATTACK_TYPE_INIT":0,
    "ATTACK_TYPE_3":1,
    "ATTACK_TYPE_4":2,
    "ATTACK_TYPE_5":3,
    "ATTACK_TYPE_6":4
}

exports.PLAY_TIME = {
    "PLAY_TIME_1":60,
    "PLAY_TIME_2":120,
    "PLAY_TIME_3":180,
    "PLAY_TIME_4":240,
    "PLAY_TIME_5":300
}