const RES_CODE = {
    "SUCCESS": 0,
    "PANCHANGE_DB_RESET_FAIL": 101,
    "INVALID_PARAM": 102,
    "GET_ROOM_LIST_FAIL": 103,
    "GET_ROOM_DETAIL_FAIL": 104,
    "CREATE_FREE_ROOM_NUMBER_FAIL": 105,  // 자유대전 방번호 저장하기 오류
    "CREATE_FREE_ROOM_HOST_FAIL": 106,  // 자유대전 호스트 정보 저장하기 오류
    "CREATE_FREE_ROOM_DETAIL_FAIL": 107,  // 자유대전 디테일 저장하기 오류
    'SLANG_WORD_CHECKED': 108,
    'ALREADY_CLAN_CREATED': 109,
    "CREATE_CLAN_ROOM_NUMBER_FAIL": 110, // 클랜방 번호 저장하기 오류
    "CREATE_CLAN_ROOM_HOST_FAIL": 111, // 클랜방 호스트정보 저장하기 오류
    "CREATE_CLAN_ROOM_CLANINFO_FAIL": 112, // 클랜정보 저장하기 오류
    "CREATE_CLAN_ROOM_DETAIL_FAIL": 113, // 룸디테일 정보 저장하기 오류
    "DELETE_ROOM_FAIL": 114,
    "ROOM_DETAIL_SET_FAIL": 115,
    "ROOM_SEARCH_RESULT_EMPTY": 116,
    "DELETE_HOST_ROOM_FAIL": 117,
    "SAVE_TO_HOST_KEY_FAIL": 118,
    'DELETE_CLAN_ROOM_FAIL': 119,
    "SAVE_TO_CLAN_KEY_FAIL": 120,
    "ROOM_NOT_CLAN": 121,
    "CLAN_NAME_FAIL": 145,

    "GC_DB_RESET_FAIL": 122,
    "GC_METHOD_FAIL": 123,

    "PAN_GAME_ROOM_FULL": 124,
    "PAN_GAME_ROOM_IS_PLAY": 125,
    "PAN_GAME_ROOM_COUNT_GET_FAIL": 126,
    "PAN_GAME_ROOM_USER_ADD_FAIL": 127,
    "PAN_GAME_USER_DETAIL_FAIL": 128,
    "PAN_GAME_ROOM_COUNT_FAIL": 129,
    "PAN_GAME_NOTMATCHPWD": 130,
    "PAN_GAME_ROOM_NOTMYCLAN": 131,
    "PAN_GAME_ROOM_RED_USER_FAIL": 132,
    "PAN_GAME_ROOM_BLUE_USER_FAIL": 133,
    "PAN_GAME_USER_DELETE_FAIL": 134,
    "PAN_GAME_USER_IS_NOT_EXIST": 135,
    "PAN_GAME_METHOD_FAIL": 136,
    "PAN_GAME_NO_MASTER": 137,

    "PAN_GAME_BOARD_LIST_SET_FAIL": 138,
    "PAN_GAME_RANK_LIST_ADD_FAIL": 139,
    "PAN_GAME_SET_ROOM_SCORE_FAIL": 140,
    "ADD_EVENT_TIME_LIST_FAIL": 141,
    "ADD_EVENT_QUIZ_FAIL": 142,
    "GET_QUIZ_FAIL": 143,
    "PAN_GAME_RANK_LIST_GET_FAIL": 144,
    "PAN_GAME_DELETE_METHOD_FAIL": 146,
    "API_SERVER_ERROR": 147,

    "ADD_DATA_TO_ARRAY_FAIL": 148,
    "GET_LIST_FROM_ARRAY_FAIL": 149,
    "REMOVE_ELEMENT_IN_ARRAY_FAIL": 150,

    "GET_HASH_VALUE_FAIL": 151,

    "PANCHANGE_SEARCH_ROOM_NUM_REDIS": 4400,
    "PANCHANGE_SEARCH_ROOM_NUM_EMPTY": 4401,
    "PANCHANGE_SEARCH_NICK_NAME_REDIS1": 4410,
    "PANCHANGE_SEARCH_NICK_NAME_REDIS1_RES": 4411,
    "PANCHANGE_SEARCH_NICK_NAME_REDIS2": 4412,
    "PANCHANGE_SEARCH_NICK_NAME_REDIS2_RES": 4413,

    "PANCHANGE_AUTO_ENTER_REDIS": 4500,
    "PANCHANGE_AUTO_ENTER_NOT_ENOUGH": 4502,
    "PANCHANGE_AUTO_ENTER_REDIS_RES": 4501,

    "PANCHANGE_SEARCH_CLAN_ROOM_REDIS": 4200,
    "PANCHANGE_SEARCH_CLAN_ROOM_EMPTY": 4201,
    "PANCHANGE_SEARCH_CLAN_ROOM_EMPTY2": 4202
}

module.exports = RES_CODE;