exports.PACKET_ERR = {
    "SUCCESS": 0,
    "WRITE_SESSION_ID_REDIS_DB_CONN": 1000,
    "WRITE_SESSION_ID_GET_REDIS_DB": 1001,
    "WRITE_SESSION_ID_GET_MYSQL_DB": 1002,

    "WRITE_SESSION_ID_MYSQ_DB_CONN": 1002,
    "WRITE_SESSION_ID_QUERY": 1003,


    "READ_SESSION_ID_REDIS_DB_CONN": 2000,
    "READ_SESSION_ID_MYSQL_DB_CONN": 2001,
    "READ_SESSION_ID_GET_MYSQL_DB": 2002,
    "READ_SESSION_WRITE_REDIS": 2003,


    "WRITE_SETCOIN_RESULT_MYSQL_DB_CONN": 2100,
    "WRITE_SETCOIN_RESULT_MYSQL_DB_QUERY": 2101,

    "READ_SETCOIN_USERINFO_REDIS_DB": 2200,
    "READ_SETCOIN_USERINFO_NULL": 2201,
    "READ_SETCOIN_USERINFO_GET_MYSQL_DB": 2202,
    "READ_SETCOIN_WRITE_USERINFO_REDIS": 2203,
    "THERE_IS_NOT_USER_DATA_IN_REDIS": 2204,


    "SETCOIN_ROOMNUMBER_REDIS": 2300,
    "SETCOIN_ROOMNUMBER_REDIS2": 2301,
    "SETCOIN_ROOMNUMBER_EMPTY": 2302,
    "SETCOIN_ROOMNUMBER_EMPTY2": 2303,

    "SETCOIN_RETURN_ROOM_NUMBER_REDIS": 2400,
    "SETCOIN_RETURN_ROOM_NUMBER_REDIS_WRITE": 2401,

    "SETCOIN_DELETE_ROOM_REDIS1": 2500,
    "SETCOIN_DELETE_ROOM_REDIS2": 2501,
    "SETCOIN_DELETE_ROOM_REDIS3": 2502,
    "SETCOIN_DELETE_ROOM_REDIS4": 2503,
    "SETCOIN_DELETE_ROOM_REDIS5": 2504,

    "GET_TOTAL_ROOM_LIST": 2500,



    "GAME_READ_BY_NICNAME_USERINFO_REDIS_DB": 3000,
    "GAME_READ_BY_NICNAME_USERINFO_GET_MYSQL_DB": 3001,
    "GAME_READ_BY_NICNAME_WRITE_USERINFO_REDIS": 3002,

    "MYSQL_READ_BY_SESSION_CONNECT": 3100,
    "MYSQL_READ_BY_SESSION_NOT_INFO": 3101,
    "MYSQL_READ_BY_SESSION_QUERY": 3102,


    "PANCHANGE_ROOMNUMBER_REDIS": 4000,
    "PANCHANGE_ROOMNUMBER_REDIS2": 4001,
    "PANCHANGE_ROOMNUMBER_EMPTY": 4002,
    "PANCHANGE_ROOMNUMBER_EMPTY2": 4003,

    "PANCHANGE_RETURN_ROOM_NUMBER_REDIS": 4100,
    "PANCHANGE_RETURN_ROOM_NUMBER_REDIS_WRITE": 4101,

    "PANCHANGE_SEARCH_CLAN_ROOM_REDIS": 4200,
    "PANCHANGE_SEARCH_CLAN_ROOM_EMPTY": 4201,
    "PANCHANGE_SEARCH_CLAN_ROOM_EMPTY2": 4201,
    "PANCHANGE_NOTHIG_CLAN_INFO": 4202,


    "PANCHANGE_GET_TOTAL_ROOM_LIST_REDIS": 4300,

    "PANCHANGE_SEARCH_ROOM_NUM_REDIS": 4400,
    "PANCHANGE_SEARCH_ROOM_NUM_EMPTY": 4401,

    "PANCHANGE_AUTO_ENTER_REDIS": 4500,
    "PANCHANGE_AUTO_ENTER_REDIS_RES": 4501,
    "PANCHANGE_AUTO_ENTER_NOT_ENOUGH": 4502,


    "PANCHANGE_DELETE_ROOM_REDIS": 4600,
    "PANCHANGE_DELETE_ROOM_REDIS2": 4601,
    "PANCHANGE_DELETE_ROOM_REDIS3": 4602,
    "PANCHANGE_DELETE_ROOM_REDIS4": 4603,

    "PANCHANGE_CREATE_ROOM_NO_CLAN_REDIS": 4700,
    "PANCHANGE_CREATE_ROOM_NO_CLAN_REDIS1": 4701,
    "PANCHANGE_CREATE_ROOM_NO_CLAN_REDIS1_RES": 4702,
    "PANCHANGE_CREATE_ROOM_NO_CLAN_REDIS2": 4703,
    "PANCHANGE_CREATE_ROOM_NO_CLAN_REDIS2_RES": 4704,


    "PANCHANGE_CREATE_ROOM_CLAN_REDIS": 4710,
    "PANCHANGE_CREATE_ROOM_CLAN_REDIS_RES": 4711,

    "PANCHANGE_CREATE_ROOM_CLAN_REDIS1": 4712,
    "PANCHANGE_CREATE_ROOM_CLAN_REDIS1_RES1": 4713,
    "PANCHANGE_CREATE_ROOM_CLAN_REDIS2": 4714,
    "PANCHANGE_CREATE_ROOM_CLAN_REDIS2_RES2": 4715,
    "PANCHANGE_CREATE_ROOM_CLAN_REDIS3": 4716,
    "PANCHANGE_CREATE_ROOM_CLAN_REDIS3_RES": 4717,
    "PANCHANGE_CREATE_ROOM_CLAN_REDIS3_ALREADY_MAKE_ROOM_ERR": 4718,

    "PANCHANGE_CHANGE_ROOM_OPTION_REDIS": 4810,
    "PANCHANGE_CHANGE_ROOM_OPTION_REDIS_RES": 4819,
    "PANCHANGE_CHANGE_IS_PLAY_REDIS": 4820,
    "PANCHANGE_CHANGE_IS_PLAY_REDIS_RES": 4821,



    "PANCHANGE_REQUEST_ROOMLIST_PARAMETER": 4800,
    "PANCHANGE_REQUEST_ROOMLIST_REDIS1": 4801,
    "PANCHANGE_REQUEST_ROOMLIST_REDIS1_RES": 4802,
    "PANCHANGE_REQUEST_ROOMLIST_REDIS2": 4803,
    "PANCHANGE_REQUEST_ROOMLIST_REDIS2_RES": 4804,

    "PANCHANGE_REQUEST_UPDATE_CLAN_B_NAME_REDIS": 4805,
    "PANCHANGE_REQUEST_UPDATE_CLAN_B_NAME_REDIS_RES": 4806,

    "PANCHANGE_REQUEST_USER_COUNT_REDIS": 4900,
    "PANCHANGE_REQUEST_USER_COUNT_REDIS_RES": 4901,

    "PANCHANGE_UPDATE_USER_COUNT_REDIS": 5000,
    "PANCHANGE_UPDATE_USER_COUNT_REDIS_RES": 5001,
    "PANCHANGE_NO_MYCLAN_FROM_ROOM": 5002,

    "SETCOIN_RANKING_REDIS": 5100,
    "SETCOIN_RANKING_REDIS_RES": 5101,

    "PANCHANGE_RANKING_REDIS": 5200,
    "PANCHANGE_RANKING_REDIS_RES": 5201,

    "MOLE_RANKING_REDIS": 5300,
    "MOLE_RANKING_REDIS_RES": 5301,
    "MOLE_RANKING_REDIS_REDIS1": 5302,
    "MOLE_RANKING_REDIS_REDIS1_RES": 5303,
    "MOLE_RANKING_REDIS_REDIS2": 5304,
    "MOLE_RANKING_REDIS_REDIS2_RES": 5305,
    "MOLE_RANKING_REDIS_MYSQL": 5306,
    "MOLE_RANKING_REDIS_MYSQL_QUERY": 5307,
    "MOLE_RANKING_REDIS_MYSQL_QUERY_RES": 5308,
    "MOLE_RANKING_REDIS_SCHOOL_MYSQL": 5309,
    "MOLE_RANKING_REDIS_SCHOOL_MYSQL_QUERY": 5310,
    "MOLE_RANKING_MYSQL": 5311,
    "MOLE_RANKING_MYSQL_QUERY": 5312,


    "PANCHANGE_RANKING_REDIS": 5400,
    "PANCHANGE_RANKING_REDIS_RES": 5401,
    "PANCHANGE_RANKING_REDIS_REDIS1": 5402,
    "PANCHANGE_RANKING_REDIS_REDIS1_RES": 5403,
    "PANCHANGE_RANKING_REDIS_RES2": 5404,
    "PANCHANGE_RANKING_REDIS_RES2_RES": 5405,
    "PANCHANGE_RANKING_REDIS_MYSQL": 5406,
    "PANCHANGE_RANKING_REDIS_MYSQL_QUERY": 5407,
    "PANCHANGE_RANKING_REDIS_MYSQL_QUERY_RES": 5408,
    "PANCHANGE_RANKING_REDIS_SCHOOL_MYSQL": 5409,
    "PANCHANGE_RANKING_REDIS_SCHOOL_MYSQL_QUERY": 5410,
    "PANCHANGE_RANKING_MYSQL": 5411,
    "PANCHANGE_RANKING_MYSQL_QUERY": 5412,
    "PANCHANGE_RANKING_SCHOOL_REDIS": 5413,
    "PANCHANGE_RANKING_SCHOOL_REDIS_RES": 5414,
    "PANCHANGE_RANKING_SCHOOL_MYSQL": 5415,
    "PANCHANGE_RANKING_SCHOOL_MYSQL_QUERY": 5416,

    "RANKING_REDIS_CONNECTION_ERR": 5417,

    "SETCOIN_RANKING_REDIS": 5500,
    "SETCOIN_RANKING_REDIS_RES": 5501,
    "SETCOIN_RANKING_REDIS_REDIS1": 5502,
    "SETCOIN_RANKING_REDIS_REDIS1_RES": 5503,
    "SETCOIN_RANKING_REDIS_REDIS2": 5504,
    "SETCOIN_RANKING_REDIS_REDIS2_RES": 5505,
    "SETCOIN_RANKING_REDIS_MYSQL": 5506,
    "SETCOIN_RANKING_REDIS_MYSQL_QUERY": 5507,
    "SETCOIN_RANKING_REDIS_MYSQL_QUERY_RES": 5508,
    "SETCOIN_RANKING_REDIS_SCHOOOL_MYSQL": 5509,
    "SETCOIN_RANKING_REDIS_SCHOOOL_MYSQL_QUERY": 5510,
    "SETCOIN_RANKING_MYSQL": 5511,
    "SETCOIN_RANKING_MYSQL_QUERY": 5512,
    "SETCOIN_RANKING_MYSQL_QUERY_RES": 5513,
    "SETCOIN_RANKING_REDIS_SAVE": 5514,
    "SETCOIN_RANKING_REDIS_SAVE_RES": 5515,
    "SETCOIN_RANKING_SCHOOL_REDIS": 5516,
    "SETCOIN_RANKING_SCHOOL_REDIS_RES": 5517,
    "SETCOIN_RANKING_SCHOOL_MYSQL": 5518,
    "SETCOIN_RANKING_SCHOOL_MYSQL_QUERY": 5519,

    "TYPING_RANKING_REDIS": 5600,
    "TYPING_RANKING_REDIS_RES": 5601,
    "TYPING_RANKING_REDIS_REDIS1": 5602,
    "TYPING_RANKING_REDIS_REDIS1_RES": 5603,
    "TYPING_RANKING_REDIS_REDIS2": 5604,
    "TYPING_RANKING_REDIS_REDIS2_RES": 5605,
    "TYPING_RANKING_REDIS_MYSQL": 5606,
    "TYPING_RANKING_REDIS_MYSQL_QUERY": 5607,
    "TYPING_RANKING_REDIS_MYSQL_QUERY_RES": 5608,
    "TYPING_RANKING_REDIS_SCHOOOL_MYSQL": 5609,
    "TYPING_RANKING_REDIS_SCHOOOL_MYSQL_QUERY": 5610,
    "TYPING_RANKING_REDIS_SCHOOOL_REDIS": 5611,
    "TYPING_RANKING_REDIS_SCHOOOL_REDIS_RES": 5612,

    "TYPING_POS_PRACTICE_MYSQL": 5700,
    "TYPING_POS_PRACTICE_MYSQL_QUERY": 5701,
    "TYPING_POS_PRACTICE_MYSQL_QUERY_RESULT": 5702,

    "TYPING_WORD_PRACTICE_MYSQL": 5800,
    "TYPING_WORD_PRACTICE_MYSQL_QUERY": 5801,
    "TYPING_WORD_PRACTICE_MYSQL_QUERY_RESULT": 5802,

    "TYPING_LONG_WORD_PRACTICE_MYSQL": 5900,
    "TYPING_LONG_WORD_PRACTICE_MYSQL_QUERY": 5900,
    "TYPING_LONG_WORD_PRACTICE_MYSQL_QUERY_RESULT": 5901,

    "TYPING_SETUP_MYSQL": 6000,
    "TYPING_SETUP_MYSQL_QUERY": 6001,
    "TYPING_SETUP_MYSQL_QUERY_RESULT": 6001,

    "TYPING_READ_SETUP_MYSQL": 6100,
    "TYPING_READ_SETUP_MYSQL_QUERY": 6101,
    "TYPING_READ_SETUP_MYSQL_QUERY_RESULT": 6102,

    "TYPING_READ_LONG_WORD_PRACTICE_MYSQL": 6200,
    "TYPING_READ_LONG_WORD_PRACTICE_MYSQL_QUERY": 6201,
    "TYPING_READ_LONG_WORD_PRACTICE_MYSQL_QUERY_RESULT": 6202,

    "TYPING_READ_WORD_PRACTICE_MYSQL": 6300,
    "TYPING_READ_WORD_PRACTICE_MYSQL_QUERY": 6301,
    "TYPING_READ_WORD_PRACTICE_MYSQL_QUERY_RESULT": 6302,


    "TYPING_READ_POS_PRACTICE_MYSQL": 6400,
    "TYPING_READ_POS_PRACTICE_MYSQL_QUERY": 6401,
    "TYPING_READ_POS_PRACTICE_MYSQL_QUERY_RESULT": 6402,



    "PANCHANGE_READ_RESULT_MYSQL": 6500,
    "PANCHANGE_READ_RESULT_MYSQL_RES": 6501,

    "TYPING_WRITE_GAME_RESULT_MYSQL": 6600,
    "TYPING_WRITE_GAME_RESULT_QUERY": 6601,


    "SETCOIN_READ_GAME_RESULT_MYSQL": 6700,
    "SETCOIN_READ_GAME_RESULT_MYSQL_QUERY": 6701,
    "SETCOIN_READ_GAME_RESULT_MYSQL_QUERY_RES": 6702,

    "TYPING_READ_GAME_RESULT_MYSQL": 6800,
    "TYPING_READ_GAME_RESULT_MYSQL_QUERY": 6801,
    "TYPING_READ_GAME_RESULT_MYSQL_QUERY_RES": 6802,


    "WRITE_TWO_TYPING_SPEED_MYSQL": 6900,
    "WRITE_TWO_TYPING_SPEED_QUERY": 6901,
    "WRITE_TWO_TYPING_SPEED_QUERY_RES": 6902,


    "WRITE_TWO_WORD_ACC_MYSQL": 7000,
    "WRITE_TWO_WORD_ACC_MYSQL_QUERY": 7001,
    "WRITE_TWO_WORD_ACC_MYSQL_QUERY_RES": 7001,

    "WRITE_TWO_WORD_VELOCITY_MYSQL": 7100,
    "WRITE_TWO_WORD_VELOCITY_MYSQL_QUERY": 7101,
    "WRITE_TWO_WORD_VELOCITY_MYSQL_QUERY_RES": 7102,

    "WRITE_TWO_WORD_SPEED_MYSQL": 7200,
    "WRITE_TWO_WORD_SPEED_MYSQL_QUERY": 7201,
    "WRITE_TWO_WORD_SPEED_MYSQL_QUERY_RES": 7202,


    "READ_TWO_WORD_ACC_MYSQL": 7300,
    "READ_TWO_WORD_ACC_MYSQL_QUERY": 7301,
    "READ_TWO_WORD_ACC_MYSQL_QUERY_RES": 7302,

    "READ_TWO_WORD_VELOCITY_MYSQL": 7400,
    "READ_TWO_WORD_VELOCITY_MYSQL_QUERY": 7401,
    "READ_TWO_WORD_VELOCITY_MYSQL_QUERY_RES": 7402,

    "READ_TWO_WORD_SPEED_MYSQL": 7500,
    "READ_TWO_WORD_SPEED_MYSQL_QUERY": 7501,
    "READ_TWO_WORD_SPEED_MYSQL_QUERY_RES": 7502,

    "AUTO_ENTER_REDIS1": 7600,
    "AUTO_ENTER_REDIS1_RES": 7601,
    "AUTO_ENTER_REDIS2": 7602,
    "AUTO_ENTER_REDIS2_RES": 7603,
    "AUTO_ENTER_EMPTY": 7604,

    "CREATE_ROOM_REDIS": 7700,
    "CREATE_ROOM_REDIS1": 7701,
    "CREATE_ROOM_REDIS1_RES": 7702,
    "CREATE_ROOM_REDIS2": 7703,
    "CREATE_ROOM_REDIS2_RES": 7704,

    "SETCOIN_SEARCH_HOST_NAME_REDIS": 7800,
    "SETCOIN_SEARCH_HOST_NAME_EMPTY1": 7801,
    "SETCOIN_SEARCH_HOST_NAME_REDIS2": 7802,
    "SETCOIN_SEARCH_HOST_NAME_EMPTY2": 7803,

    "SETCOIN_SEARCH_ROOM_NUM_RDIS": 7900,
    "SETCOIN_SEARCH_ROOM_NUM_EMPTY": 7901,


    "SETCOIN_CHANNEL_USERCOUNT_UPDATE_MYSQL": 8000,
    "SETCOIN_CHANNEL_USERCOUNT_UPDATE_MYSQL_QUERY": 8001,
    "SETCOIN_CHANNEL_USERCOUNT_RESET_MYSQL": 8002,
    "SETCOIN_CHANNEL_USERCOUNT_RESET_MYSQL_QUERY": 8003,

    "SETCOIN_CHANGE_ROOM_OPTION_REDIS": 9000,
    "SETCOIN_CHANGE_ROOM_OPTION_REDIS_RES": 9001,

    "SETCOIN_REQUEST_TOTAL_ROOM_LIST_NUMBER_REDIS": 9100,
    "SETCOIN_REQUEST_TOTAL_ROOM_LIST_NUMBER_REDIS_RES": 9100,

    //웹api 페킷에러 추가 cha
    "READ_RANK_SCHOOL_ERROR": 9150,
    "READ_RANK_SCHOOL_GROUP_NODATA": 9151,
    "READ_RABK_DOESNT_EXIST": 9151,
    "READ_RANK_REDIS_NODATA": 9152,
    "READ_RANK_REDIS_CONNECTION_ERR": 9153,
    "JOINCLAN_ALREADY_JOIN": 9154,
    "READ_TABLE_DOESNT_EXIST": 9155,

    //웹api 패킷에러 추가 cha
    "COMMON_QUERY_ERROR": 9160,
    "COMMON_FAIL": 1,
    "COMMON_DATABASE_ERROR": -1,
    "COMMON_REDIS_ERROR": -2,
    "COMMON_NO_DATA": 2,
    "COMMON_GET_CONNECTION_ERR": 9162,
    "COMMON_LATE_PACKET_ERR": 9163,
    "COMMON_NULL_VALUE": 9164,
    "COMMON_PACKET_OVER_TIME": 9165,

    "SDK_NO_EXSIT_GAME_FROM_REGITDB": 9170,


    //웹API 패킷에러 추가 CHA
    "WRITE_CLAN_DATA_ERROR": 9180,
    "REGIT_CLAN_SAME_CLAN_NAME": 9181,
    "JOIN_CLANMEBER_ALREDY_JOIN": 9182,
    "CLAN_CANT_DELL_ALREADY_ANOTHER_CLAN_MEMBER": 9183,
    "CLAN_CANT_RGITL_ALREADY_ANOTHER_CLAN_MEMBER": 9184,
    "JOIN_CLANMEBER_ALREDY_LEAVE": 9185,
    "CLAN_EXPLAINED_TOO_MUCH": 9186,
    "MANAGER_USER_NOT_MATCHING" : 9187,
    "SESSION_USER_NOT_MATCHING" : 9188,
    "LEAVE_CLANMEMBER":9151,
    "WRITE_CLAN_DATA_SUCESS": 0,


    "GETPOINT_MYSQL": 9200,
    "GETPOINT_MYSQL_QUERY": 9201,

    "WRITE_TWO_TYPING_SPEED_MYSQL": 9300,
    "WRITE_TWO_TYPING_SPEED_MYSQL_QUERY": 9301,
    "WRITE_TWO_TYPING_SPEED_MYSQL_QUERY_RES": 9301,

    "WRITE_POINT_LIST_MYSQL_1": 9400,
    "WRITE_POINT_LIST_MYSQL_1_QUERY": 9401,
    "WRITE_POINT_LIST_MYSQL_1_RES": 9402,
    "WRITE_POINT_LIST_MYSQL_2": 9403,
    "WRITE_POINT_LIST_MYSQL_2_QUERY": 9404,
    "WRITE_POINT_LIST_MYSQL_3_RES": 9405,

    "REQUEST_TOTAL_ROOM_LIST_REDIS": 9500,
    "REQUEST_TOTAL_ROOM_LIST_REDIS_RES": 9501,

    "ACCEPT_FRIEND_REQUEST_MSQL1": 9600,
    "ACCEPT_FRIEND_REQUEST_QUERY1": 9601,
    "ACCEPT_FRIEND_REQUEST_RES1": 9602,
    "ACCEPT_FRIEND_REQUEST_MSQL2": 9603,
    "ACCEPT_FRIEND_REQUEST_QUERY2": 9604,
    "ACCEPT_FRIEND_REQUEST_RES2": 9605,
    "ACCEPT_FRIEND_REQUEST": 9606,


    "SNED_MAIL_ERROR": 10000,

    "READ_TWO_TYPING_SPEED_MYSQL": 10100,
    "READ_TWO_TYPING_SPEED_MYSQL_QUERY": 10101,
    "READ_TWO_TYPING_SPEED_MYSQL_QUERY_RES": 10101,

    "READ_DAY_TOW_TYPING_SPEED_MYSQL": 10200,
    "READ_DAY_TOW_TYPING_SPEED_MYSQL_QUERY": 10201,
    "READ_DAY_TOW_TYPING_SPEED_MYSQL_RES": 10202,

    //금칙어....
    "CHECK_PROHIBIT_WORDS_MYSQL": 10300,
    "CHECK_PROHIBIT_WORDS_MYSQL_QUERY": 10301,
    "CHECK_PROHIBIT_WORDS_MYSQL_QUERY_RES": 10302,
    "CHECK_PROHIBIT_WORDS_NO_WORDS": 10303, //금칙어 사용 중
    "CHECK_PROHIBIT_WORDS_SPECIAL_WORDS": 10304, //특수문자 사용 중

    //룸정보에서 클랜명 갱신
    "WRITE_RESET_CLAN_NAME_REDIS1": 10400,
    "WRITE_RESET_CLAN_NAME_NO_ROOM": 10401,
    "WRITE_RESET_CLAN_NAME_ROOM_NO_CLAN": 10402,
    "WRITE_RESET_CLAN_NAME_REDIS2": 10403,
    "WRITE_RESET_CLAN_NAME_REDIS2_RES": 10404,
    "WRITE_RESET_CLAN_NAME_REDIS3": 10405,
    "WRITE_RESET_CLAN_NAME_REDIS3_RES": 10406,
    "WRITE_RESET_CLAN_NAME_REDIS4": 10407,
    "WRITE_RESET_CLAN_NAME_REDIS4_RES": 10408,


    "WRITE_LOG_MYSQL": 50000,
    "WRITE_LOG_MYSQL_QUERY": 50001,
    "WRITE_LOG_MYSQL_QUERY_RES": 50002,
    "MYSQL_READ_BY_SESSION_NOT_MATCH": 50004,
    "MYSQL_READ_BY_CLAN_NOT_MATCH": 50005,

    "SDK_REDIS_ERR_ADD": 50010,
    "SDK_REDIS_ERR_ADD_RESULT": 50011,
    "SDK_ERR_SAVE_GAME_USING_LOG_REDIS1": 50012,

    "SDK_ERR_NO_CONFIRM_SERVICE_GAME": 50013,
    "SDK_ERR_NO_MATCHING_SESSION": 50014,
    "SDK_NOT_REGITED_GAME": 50015,

    "CRYPTO_KEY": "dhwkekdyend123dsr23",

}